### ISSUE TITLE
[dxl_armed_turtlebot / euslisp] display-checkerboard.l の/image_markerの結果の確認の仕方について 

### ISSUE THREAD

**Issue by kochigami** [jsk-enshu/robot-programming#74]
```
roslaunch turtlebot_bringup minimal.launch
roslaunch turtlebot_bringup 3dsensor.launch 
roslaunch roseus_tutorials checkerboard_detector.launch rect0_size_x:=0.025 rect0_size_y:=0.025 grid0_size_x:=5 grid0_size_y:=4 translation0:="0 0 0" image:=image_rect_mono group:=/camera/rgb frame_id:=camera_rgb_frame
roseus display-checkerboard.l
```
を行い，表示されたCheckerBoard Detector という名前のカメラ画像・euslisp実行端末の表示文字列から，チェッカーボード検出の確認をしました．

dxl_armed_turtlebot/euslisp/display-checkerboard.l の，
チェッカーボードを見つけた後のobjectdetection-cb の処理の以下の部分，

```
 ;; image_markerを出力                                                       
    (dolist (obj-pose (send msg :objects))
      (setq type (send obj-pose :type))
      (unless (eq (char type 0) #\/) (setq type (concatenate string "/" type)))
      (setq ret (ros::tf-pose->coords (send obj-pose :pose)))
      (send mrk :type image_view2::ImageMarker2::*FRAMES*)
      (send mrk :frames (list type))
      (send *tfb* :send-transform ret frame-id type)
      (ros::ros-info "~A ~A ~A" ret frame-id type)
      (ros::publish "image_marker" mrk))
```
で新たに立ち上げたimage_view2 のビューワに何かマーカが出るのかと思うのですが，
```rosrun image_view2 image_view2 image:=/camera/rgb/image_raw camera_info:=/camera/rgb/camera_info```　すると，
```
[ERROR] [1458459132.769960178]: [image_view2] TF exception:
Lookup would require extrapolation into the future.  Requested time 1458459131.754825312 but the latest data is at time 1458459129.735534750, when looking up transform from frame [test_object] to frame [camera_rgb_optical_frame]
```
とチェッカーボードとカメラの座標変換がうまくいっていないとエラーが出つづけ，マーカは出ません．

``` 
rostopic echo /image_marker
header: 
  seq: 0
  stamp: 
    secs: 0
    nsecs: 0
  frame_id: ''
ns: ''
id: 0
type: 5
action: 0
position: 
  x: 0.0
  y: 0.0
  z: 0.0
position3D: 
  header: 
    seq: 0
    stamp: 
      secs: 0
      nsecs: 0
    frame_id: ''
  point: 
    x: 0.0
    y: 0.0
    z: 0.0
pose: 
  header: 
    seq: 0
    stamp: 
      secs: 0
      nsecs: 0
    frame_id: ''
  pose: 
    position: 
      x: 0.0
      y: 0.0
      z: 0.0
    orientation: 
      x: 0.0
      y: 0.0
      z: 0.0
      w: 0.0
scale: 0.0
width: 0.0
outline_color: 
  r: 0.0
  g: 0.0
  b: 0.0
  a: 0.0
filled: 0
fill_color: 
  r: 0.0
  g: 0.0
  b: 0.0
  a: 0.0
lifetime: 
  secs: 0
  nsecs: 0
arc: 0
angle: 0.0
points: []
points3D: 
  header: 
    seq: 0
    stamp: 
      secs: 0
      nsecs: 0
    frame_id: ''
  points: []
outline_colors: []
frames: ['/test_object']
text: ''
left_up_origin: False
ratio_scale: False
---
```
となっており，座標がうまく渡されていません．
しかしこの変換は，display-checkerboard.lの中の，
```
  (send *tfb* :send-transform ret frame-id type) ;; ret: checkerboardのカメラ相対の座標 frame-id: /camera_rgb_frame type: /test_object (checkerboard) 
```
で行われているのではないかと思います．
勉強不足ですので，分かったらissueを閉じます．
